### ISSUE TITLE
.eslintrc file not placed under /test by default

### ISSUE THREAD

**Issue by jhusain** [DonutEspresso/generator-npm#2]
This caused my editor to be confused because "describe" was not in scope.

**Comment by DonutEspresso** [comment]
Hm, I used this just the other day, the current template does put an .eslintrc under test by default:
https://github.com/DonutEspresso/generator-npm/blob/master/app/index.js#L201

cc @yunong is this something you've seen?

**Comment by jhusain** [comment]
Might've been my bad. I might not have opted for test generation. If I had chosen not to, would it have generated the test folder?  It generated a test folder for me, along with a placeholder. Under the circumstances I would've expected the configuration file.

**Comment by DonutEspresso** [comment]
The test folder is always generated, the prompt about the test file only changes how the Makefile invokes the test. Can you give it another try and let me know? I just tried it again locally and it looks ok, but there may be something specific to your setup.

**Comment by jhusain** [comment]
Just tried a fresh project and I see it. Not sure what happened. Sorry for the noise.
